name: Validate Handles

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  validate:
    if: github.repository_owner == 'marchof'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - run: |
        mvn --no-transfer-progress package exec:java -Dexec.mainClass=org.javabubble.generator.HandleValidator
      env:
        API_AUTH_GITHUB: ${{ secrets.API_AUTH_GITHUB }}
        API_AUTH_TWITTER: ${{ secrets.API_AUTH_TWITTER }}
      working-directory: generator
    - uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "Cleanup handles"
        branch: "cleanup-handles"
        title: "Cleanup Handles"

